# -*- coding: utf-8 -*-
"""Crop_recomondation_Analysis ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6VXjS2mJpL9IeOyvhj3iU-ShsqNN1pH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#import the data set
df = pd.read_csv("/content/Crop_recommendation.csv")

df.head()

df.tail() #reviewing last 5 rows.

df.shape

df.info()

df.describe() #stastical information

df.dtypes

df.isnull().sum() #checking null values

df.hist(bins=15,figsize=(10,10))

sns.boxplot(y='temperature',data=df)

sns.boxplot(y='humidity',data=df)

sns.boxplot(y='ph',data=df)

sns.boxplot(y='N',data=df)

sns.boxplot(y='K',data=df)

sns.boxplot(y='P',data=df)

def remove_outliers(col_name):
  sorted(col_name)
  Q1,Q3 = col_name.quantile([0.25,0.75])
  IQR = Q3-Q1
  lower_range = Q1-(1.5*IQR)
  upper_range = Q3+(1.5*IQR)
  return lower_range,upper_range

low,high = remove_outliers(df['P'])

df['P'] = np.where(df['P']>high,high,np.where(df['P']<low,low,df['P']))

sns.boxplot(y='P',data=df)

#Humidity VS Temperature
plt.figure(figsize=(10,8))
sns.scatterplot(x='humidity',y='temperature',data=df,hue='label')
plt.show()

plt.figure(figsize=(12, 6))
sns.violinplot(x="label", y="ph", data=df, palette="Set3")
plt.title("Violin Plot of Soil pH by Crop Type")
plt.xticks(rotation=90)
plt.show()

plt.figure(figsize=(10,10))
sns.barplot(y='label',x='K',data=df)

df.groupby(['label'])['P'].mean().sort_values(ascending=False)